
import numpy as np
from parms import g, U0t, Ut, Jt
from numba import jit, int64, float64, complex128


@jit(complex128(complex128[:,:],int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E1(f, i, n, mu, U0, dU, J):
	Ef = 0
	Ef = -(mu*n*f[i,n].conjugate()*f[i,n]) - 0.5*n*U0*f[i,n].conjugate()*f[i,n] - 0.5*n*f[i,n].conjugate()*dU[i]*f[i,n] + 0.5*U0*f[i,n].conjugate()*f[i,n]*pow(n,2.) + 0.5*f[i,n].conjugate()*dU[i]*f[i,n]*pow(n,2.)
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E2(f, i, j1, j2, n, mu, U0, dU, J):
	Ef = 0
	Ef = -(f[i,1 + n].conjugate()*f[j2,n].conjugate()*f[i,n]*f[j2,1 + n]*g(n,1 + n)*J[i]) - f[i,1 + n].conjugate()*f[j1,n].conjugate()*f[i,n]*f[j1,1 + n]*g(n,1 + n)*J[j1]
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E3(f, i, j1, j2, n, m, mu, U0, dU, J):
	Ef = 0
	Ef = -(n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*J[i]*pow(1 - m + n,-1.)*pow(U0,-1.)) - f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*J[i]*pow(1 - m + n,-1.)*pow(U0,-1.) + m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*J[i]*pow(1 - m + n,-1.)*pow(U0,-1.) - n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E4(f, i, j1, j2, k1, k2, n, m, p, mu, U0, dU, J):
	Ef = 0
	if (1 + n == p and m == 2 + p):
		Ef += n*f[i,1 + p].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + p*f[i,1 + p].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + f[i,1 + p].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - m*f[i,1 + p].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - p*f[i,1 + p].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (m == p and n == 1 + p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,p]*f[j1,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.)) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,p]*f[j1,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,p]*f[j1,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,p]*f[j1,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,p]*f[j1,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (1 + n == p and m == 2 + p):
		Ef += n*f[i,1 + p].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + p*f[i,1 + p].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + f[i,1 + p].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - m*f[i,1 + p].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - p*f[i,1 + p].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (m == p and n == 1 + p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,p]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.)) - p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,p]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,p]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,p]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,p]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (n == p and m == 1 + p):
		Ef += n*f[i,p].conjugate()*f[j1,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - p*f[i,p].conjugate()*f[j1,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + f[i,p].conjugate()*f[j1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - m*f[i,p].conjugate()*f[j1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + p*f[i,p].conjugate()*f[j1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (n == p and m == 1 + p):
		Ef += n*f[i,p].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - p*f[i,p].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + f[i,p].conjugate()*f[j2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - m*f[i,p].conjugate()*f[j2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + p*f[i,p].conjugate()*f[j2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j2,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j2,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) + m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.) - p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,p]*g(n,m)*g(p,1 + p)*pow(1 - m + n,-2.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (1 + n == p):
		Ef += n*f[i,1 + p].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + p].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + p].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + p].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + p].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (n == 1 + p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,p]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)) - p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,p]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,p]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,p]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,p]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (1 + n == p):
		Ef += n*f[i,1 + p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (n == 1 + p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,p]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,p]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,p]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,p]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,p]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == 1 + p):
		Ef += n*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[k1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[i]*f[i,n]*f[j1,p]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,p]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,p]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,p]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,p]*f[k1,1 + p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == 1 + p):
		Ef += n*f[i,1 + n].conjugate()*f[j2,1 + p].conjugate()*f[k2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + n].conjugate()*f[j2,1 + p].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + n].conjugate()*f[j2,1 + p].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j2,1 + p].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j2,1 + p].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[i]*f[i,n]*f[j2,p]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,p]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,p]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,p]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,p]*f[k2,1 + p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (n == p):
		Ef += n*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,1 + p]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[i]*f[i,1 + p]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j1]*f[i,1 + p]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j1]*f[i,1 + p]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,1 + p].conjugate()*dU[j2]*f[i,1 + p]*f[j1,m]*f[j2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (n == p):
		Ef += n*f[i,p].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,p].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,p].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,p].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,p].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - n*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) - f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,1 + p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j1,p]*f[j2,m]*g(n,m)*g(p,1 + p)*J[i]*J[j1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.)) - f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,1 + p].conjugate()*dU[k1]*f[i,n]*f[j1,1 + p]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == 2 + p):
		Ef += n*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,1 + p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,1 + p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,1 + p].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,p]*g(n,m)*g(p,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == p):
		Ef += -(n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,1 + p].conjugate()*dU[i]*f[i,n]*f[j2,1 + p]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.)) - f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,1 + p].conjugate()*dU[k2]*f[i,n]*f[j2,1 + p]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.)
	
	if (m == 2 + p):
		Ef += n*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,1 + p].conjugate()*dU[i]*f[i,n]*f[j2,m]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - m*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) - p*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,1 + p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.) + p*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,1 + p].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,p]*g(n,m)*g(p,1 + p)*J[i]*J[j2]*pow(1 - m + n,-2.)*pow(U0,-2.)
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,int64,int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E5(f, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J):
	Ef = 0
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) + 0.5*q*f[i,q].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) - 0.5*p*f[i,q].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) + 0.5*q*f[i,q].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) - 0.5*p*f[i,q].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (n == p and m == q):
		Ef += -0.5*p*f[i,p].conjugate()*f[j1,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) - 0.5*f[i,p].conjugate()*f[j1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) + 0.5*q*f[i,p].conjugate()*f[j1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[j1],2.)
	
	if (n == p and m == q):
		Ef += -0.5*p*f[i,p].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) - 0.5*f[i,p].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) + 0.5*q*f[i,p].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)*pow(J[i],2.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*p*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*p*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == q):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*p*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == q):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*p*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (n == p):
		Ef += -0.5*p*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (n == p):
		Ef += -0.5*p*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == p):
		Ef += 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == 2 + p):
		Ef += -0.5*p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == p):
		Ef += 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	
	if (m == 2 + p):
		Ef += -0.5*p*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) - 0.5*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.) + 0.5*q*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(-1 - p + q,-1.)*pow(U0,-2.)
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,int64,int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E6(f, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J):
	Ef = 0
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[j1],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[j1],2.)
	
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[i],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j2,p].conjugate()*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[i],2.)
	
	if (n == p and m == q):
		Ef += -0.5*f[i,p].conjugate()*f[j1,q].conjugate()*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[j1],2.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[j1],2.)
	
	if (n == p and m == q):
		Ef += -0.5*f[i,p].conjugate()*f[j2,q].conjugate()*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[i],2.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow(J[i],2.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == q):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == q):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (n == p):
		Ef += -0.5*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (n == p):
		Ef += -0.5*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == p):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == 2 + p):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == p):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)
	
	if (m == 2 + p):
		Ef += -0.5*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)
	return Ef

@jit(complex128(complex128[:,:],int64,int64,int64,int64,int64,int64,int64,int64,int64,float64,float64,float64[:],float64[:]), nopython=True, cache=True)
def E7(f, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J):
	Ef = 0
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*n*f[i,q].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*q*f[i,q].conjugate()*f[j1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*f[i,q].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*m*f[i,q].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*p*f[i,q].conjugate()*f[j1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.)
	
	if (m == p and n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.)
	
	if (m == 2 + p and 2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*n*f[i,q].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*q*f[i,q].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*f[i,q].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*m*f[i,q].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*p*f[i,q].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.)
	
	if (n == p and m == q):
		Ef += 0.5*n*f[i,p].conjugate()*f[j1,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*p*f[i,p].conjugate()*f[j1,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*m*f[i,p].conjugate()*f[j1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*q*f[i,p].conjugate()*f[j1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[j1],2.)
	
	if (n == p and m == q):
		Ef += 0.5*n*f[i,p].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*p*f[i,p].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*m*f[i,p].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*q*f[i,p].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) + 0.5*m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)*pow(J[i],2.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,-1 + q]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*n*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,q].conjugate()*f[j1,p].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,1 + p]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (n == q):
		Ef += 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,-1 + q]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (2 + n == q):
		Ef += -0.5*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*n*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,q].conjugate()*f[j1,-1 + m].conjugate()*f[j2,p].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == q):
		Ef += 0.5*n*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[i]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,p].conjugate()*dU[k1]*f[i,n]*f[j1,-1 + q]*f[k1,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == q):
		Ef += 0.5*n*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[i]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,1 + n].conjugate()*f[j2,q].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[i]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[j2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,p].conjugate()*dU[k2]*f[i,n]*f[j2,-1 + q]*f[k2,1 + p]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (n == p):
		Ef += 0.5*n*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,p].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,n]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[i]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j1]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j1]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[j2,q].conjugate()*dU[j2]*f[i,1 + p]*f[j1,m]*f[j2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (n == p):
		Ef += 0.5*n*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,p].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,n]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*n*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[i]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j1]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,q].conjugate()*f[j2,-1 + m].conjugate()*dU[j2]*f[i,1 + p]*f[j1,-1 + q]*f[j2,m]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == p):
		Ef += -0.5*n*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[i]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j1,-1 + m].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,1 + p]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == 2 + p):
		Ef += 0.5*n*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[i]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[j1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,1 + n].conjugate()*f[j1,p].conjugate()*f[k1,q].conjugate()*dU[k1]*f[i,n]*f[j1,m]*f[k1,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[j1]*J[k1]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == p):
		Ef += -0.5*n*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[i]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*m*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*p*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*q*f[i,1 + n].conjugate()*f[j2,-1 + m].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,1 + p]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	
	if (m == 2 + p):
		Ef += 0.5*n*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[i]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*m*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*p*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[j2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) - 0.5*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.) + 0.5*q*f[i,1 + n].conjugate()*f[j2,p].conjugate()*f[k2,q].conjugate()*dU[k2]*f[i,n]*f[j2,m]*f[k2,-1 + q]*g(n,m)*g(-1 + q,1 + p)*J[i]*J[j2]*pow(1 - m + n,-1.)*pow(U0,-1.)*pow((1 - m + n)*U0 + (-1 - p + q)*U0,-1.)
	return Ef

@jit(complex128(complex128[:],int64,int64,float64,float64,float64[:]), nopython=True, cache=True)
def E(f, L, nmax, mu, W, xi):
	fin = f.reshape((L, nmax+1))
	U0 = U0t(W)
	Wi = W * xi
	U = Ut(Wi)
	dU = U - U0
	J = Jt(Wi)
	Ef = 0


	for i in range(L):
		k1 = (i-2) % L
		j1 = (i-1) % L
		j2 = (i+1) % L
		k2 = (i+2) % L
		for n in range(nmax+1):
			Ef += E1(fin, i, n, mu, U0, dU, J)
			if n < nmax:
				Ef += E2(fin, i, j1, j2, n, mu, U0, dU, J)
				for m in range(1, nmax+1):
					if n != m-1:
						Ef += E3(fin, i, j1, j2, n, m, mu, U0, dU, J)
						for p in range(nmax):
							Ef += E4(fin, i, j1, j2, k1, k2, n, m, p, mu, U0, dU, J)
							for q in range(1, nmax+1):
								if p != q-1:
									Ef += E5(fin, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J)
									if n-m == p-q:
										Ef += E6(fin, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J)
									else:
										Ef += E7(fin, i, j1, j2, k1, k2, n, m, p, q, mu, U0, dU, J)

	return Ef
